# Use docs to copy sample syntax
# https://kubernetes.io/docs/concepts/configuration/secret/#use-case-as-container-environment-variables

# Use this file for key value pair for any secret configuration in k8s
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque

# all secrets are base64 encoded values
data:
  # $ echo -n mongouser | base64
  mongo-user: bW9uZ291c2Vy
  # $ echo -n mongopassword | base64
  mongo-password: bW9uZ29wYXNzd29yZA==

